config/routes.rb
Pythia::Application.routes.draw do

  get "articles/index"

  get "articles/show"

  resources :company_mention, :only => [:index, :show], as: 'company_mentions'

  ActiveAdmin.routes(self)

  root :to => "wellcome#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :companies

end

app/models/company.rb
# coding: utf-8
class Company < ActiveRecord::Base
  investcafe_db = Settings.investcafe_db
  establish_connection = investcafe_db
  
  has_many :company_mentions
  has_many :company_synonyms
  has_many :articles, :through => :company_mentions

  def self.search_by_word word
    companies = Company.all
    companies.each do |company|
      return company if company.name_compare word
    end
    false
  end

  def name_compare word
    # word.to_s.mb_chars.upcase.index self.name.to_s.mb_chars.upcase
    word.to_s.mb_chars.upcase == self.name.to_s.mb_chars.upcase
  end

  def get_mentions_by_article article
    company_mentions.by_article article
  end

  def when_and_count_mention
    data = {}
    dates_and_counters.each do |record|
      day = record.date_created
      counter = record.count_articles
      data[day] = counter
    end
    data
  end

  def count_mention_articles
    company_mentions.select('count(company_id)').where('company_id = ?', self.id).group('article_id')
  end

  def count_publication
    company_mentions.select("count(*)").where('company_id = ?', self.id).group('article_id').all.count
  end

  def to_s
    self.name
  end
end

app/controllers/companies_controller.rb
# conding: utf-8
class CompaniesController < ApplicationController
  respond_to :html

  def index
    @companies = Company.order(:name).page params[:page]
    respond_with @companies
  end
  
  def show
    @company = Company.find params[:id]
    respond_with @company
  end

end

app/helpers/company_helper.rb
module CompanyHelper
end

app/views/companies/index.html.haml
.page-header
  %h1 Компании

%ul
- @companies.each do |company|
  %li=link_to company, company_path(company)

= paginate @companies

app/views/companies/show.html.haml
%h2= @company.name

%h3
  Упоминания (#{@company.company_mentions.count})
  %ul
    - @company.company_mentions.each do |cm|
      %li= link_to cm, cm
      
%h3
  - @collect_article = @company.articles.uniq
  Статьи (#{@collect_article.count})
  %ul
    - @collect_article.each do |a|
      %li= link_to a.title, a.url