config/routes.rb
Pythia::Application.routes.draw do

  get "articles/index"

  get "articles/show"

  resources :company_mention, :only => [:index, :show], as: 'company_mentions'

  ActiveAdmin.routes(self)

  root :to => "wellcome#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :companies

end

app/views/layouts/_footer.html.haml
%footer.container
  .content
    %hr
      %p © Инвесткафе 2012

app/views/layouts/_menu.html.haml
.well.sidebar-nav
  %h3 Sidebar
  %ul.nav.nav-list
    %li.nav-header Sidebar
    %li= link_to "Яндекс", "http://yandex.ru"
 

app/views/layouts/_navigation.html.haml
= link_to "Pythia", root_path, :class => 'brand'

= bootstrap_navigation :type=>'' do |nav|
  - nav.link_to 'Компании', companies_path
  - nav.link_to  'Упоминания', company_mentions_path
  - nav.link_to 'Управление', admin_dashboard_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Pythia"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span9
              = yield
            .span3
              = render 'layouts/menu'
    =render 'layouts/footer'